version: '3'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    hostname: redpanda
    ports:
      - "19092:19092"
      - "9644:9644"
      - "9092:9092"
    environment:
      - REDPANDA_RPC_SERVER_LISTEN_ADDR=0.0.0.0
      - REDPANDA_KAFKA_ADDRESS=0.0.0.0:19092
      - REDPANDA_SEED_SERVERS=[]
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:19092,OUTSIDE://localhost:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - kafka-net
  
  # Console de administração Redpanda (opcional, mas útil para depuração)
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      - REDPANDA_BROKERS=redpanda:19092
      - KAFKA_BROKERS=redpanda:19092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  redpanda_data: